
server:
  port: 50004
key:
  campaigname: Order_Confirmed(3)
  updatecampaigname: Order_Confirmed(3)
  source: Web api
  templateparams: Yes
  updatetemplateParams: Yes
  ccavenue:
    redirecturl: https://payment.eqipped.com/data/ccavResponseHandler
    cancelUrl: https://payment.eqipped.com/data/ccavResponseHandler
    # redirecturl: http://localhost:8089/CcavenuePayment/data/ccavResponseHandler
    # cancelUrl: http://localhost:8089/CcavenuePayment/data/ccavResponseHandler
    paymentApiUrl: https://payment.eqipped.com/pay/makePayment
    merchantId: 1228214
    enable: ENABLE_YES
    # enable: DISENABLE_YES
  easebuzz:
    redirecturl:  https://payment.eqipped.com/response
    cancelUrl: https://payment.eqipped.com/response
    paymentApiUrl:  https://payment.eqipped.com/pay/initiatepayment/
    # redirecturl:  http://localhost:8090/EasebuzzCcavenuePayment/response
    # cancelUrl: http://localhost:8090/EasebuzzCcavenuePayment/response
    # paymentApiUrl:  http://localhost:8090/EasebuzzCcavenuePayment/pay/initiatepayment/
    salt: DAH88E3UWQ
    key: 2PBP7IABZ2
    baseUrl: https://testpay.easebuzz.in/
    enable: ENABLE_YES
# Eureka start
eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      #defaultZone: http://13.233.173.112:5000/eureka
      defaultZone: http://localhost:50000/eureka
# Eureka End

# Spring Start
spring:
  application:
    name: ORDER-SERVICE
  data:
    mongodb:
      uri: mongodb+srv://admin:gsk3E1ZwjWwgqAoC@cluster0.9xkoq.mongodb.net/
      database: eqipped_new
#   datasource:
#     url: jdbc:oracle:thin:@localhost:1521:xe
#     username: microserviceUserService
#     password: root
#     driverClassName: oracle.jdbc.OracleDriver
#   jpa:
#     hibernate:
#       ddl-auto: update
#     show-sql: true
#     properties:
#       hibernate:
#         dialect: org.hibernate.dialect.Oracle10gDialect
#         format_sql: true

#   config:
#     import: optional:configserver:http://localhost:5001

  mail:
    host: smtp.gmail.com
    port: 587
    username: gearloose.lab@gmail.com
    password: jijknjiwmvygfrqs
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
# Spring End

management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health

  endpoint:
    health:
      show-details: always


# Start Circuit Breakers through resilience4j server (if another service or server has down then it will return our circiut breakers methods)

resilience4j:
  circuitbreaker:
    instances:
      ratingHotelBreaker:
        registerHealthIndicator: true
        eventConsumerBufferSize: 10
        failureRateThreshold: 50
        minimumNumberOfCalls: 5
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 6s
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
        slidingWindowType: COUNT_BASED

# Retry Server through resilience4j server (if server is trying multipule time to connect to another server of another server is down then it will return to our methods)
  retry:
    instances:
      ratingHotelService:
        max-attempts: 3
        wait-duration: 5s

# Rate Limiter
  ratelimiter:
    instances:
      userRateLimiter:
        limit-refresh-period: 4s
        limit-for-period: 2
        timeout-duration: 2s
