spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        corsConfigurations:
          '[/**]':
              allowedOrigins: "*"
              allowedMethods: "*"
              allowedHeaders: "*"
      routes:
      - id: USER-SERVICE
        #uri: http://13.234.19.166:5003
        uri: http://localhost:50003
        predicates:
        - Path=/user/**
        
      - id: ORDER-SERVICE
        #uri: http://13.234.19.166:5004
        uri: http://localhost:50004
        predicates:
        - Path=/order/**
        
      - id: PRODUCT-SERVICE
        #uri: http://44.205.250.150:5005
        uri: http://localhost:50005
        predicates:
        - Path=/product/**
#         for all urls
#         - Path=/**
#         for single rest controller
#         - Path=/user/**
#         multipule urls for specific controlers
#         - Path=/hotel/**,/staffe/**

server:
  port: 50002

# spring:
#   application:
#     name: API-GATEWAY


eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      #defaultZone: http://13.233.173.112:5000/eureka/
      defaultZone: http://localhost:50000/eureka/
  
